" Vimrc file"
" https://github.com/asantosh/Tools"

set nocompatible                " no compatibility with vi
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set nobackup                    " do not keep a backup file, use versions instead
set history=50                  " keep 50 lines of command line history
"set viminfo=!,'20,\"500,c       " viminfo for 20 recent files
set title                       " show the cursor position all the time
set ruler                       " show the cursor position all the time
set showcmd                     " display incomplete commands
set incsearch                   " do incremental searching
set tags=tags;/                 " search path for tags
set softtabstop=4               " use 4 spaces for tabs
set noexpandtab                   " expand tabs to spaces
set shiftwidth=4                " width for indentation (used by cindent)
set cindent                     " use C indenting
set term=xterm                  " set terminal to xterm
set tty=xterm                   " set tty to xterm
set ttyfast                     " set fast terminal
set showmode                    " show mode (visual/insert/replace)
"set visualbell                  " show visual bell
set undolevels=25               " set number of undo levels
set textwidth=80                " set text width (max. no of columns)
set wrap                        " wrap longer lines (display)
set showmatch                   " set paranthesis matching
set scrolloff=2                 " always have 2 lines of context
set hlsearch                    " highlight searched text
set cmdheight=1                 " set command line height to 1
set ignorecase                  " ignore case in search patterns
set statusline=%<\|\ %f%(\ \|\ %h%)%(\ \|\ %m%)%(\ \|\ %r%)\\|%=\|\%b(0x%B)\ \|\ %l,%c%V\ \|\ %P\ \| laststatus=2
set background=light
set guifont=Monospace\ 9

:source $HOME/.vim/plugin/cscope_maps.vim
:source $HOME/.vim/plugin/autoload_cscope.vim
:source $HOME/.vim/plugin/supertab.vim
:source $HOME/.vim/plugin/taglist.vim

:syntax enable
":colorscheme elflord
highlight Statement ctermfg=DarkGreen
highlight PreProc ctermfg=DarkMagenta
highlight Type ctermfg=DarkBlue
highlight Ignore ctermfg=LightGrey
highlight LineNr ctermfg=DarkGreen
highlight rightMargin ctermfg=red

match rightMargin /.\%>80v/
match rightMargin /.\%>80v/

nnoremap <silent> <F8> :TlistToggle<CR>

"autocmd bufnewfile *.c so /home/firetide/.vim/temp.txt
"autocmd bufnewfile *.c exe "1," . 10 . "g/FILE:.*/s//FILE: " .expand("%")
"autocmd Bufwritepre,filewritepre *.c execute "normal ma"
"autocmd Bufwritepre,filewritepre *.c exe "1," . 10 . "g/LAST MODIFIED:.*/s/LAST MODIFIED:.*/LAST MODIFIED: " .strftime("%c")
"autocmd bufwritepost,filewritepost *.c execute "normal `a"
